version: '2'
services:
  hhvm:
    container_name: hhvm
    build:
      context: ./docker/hhvm
      dockerfile: Dockerfile_hvvm
    ports:
      - "8080:80"
      - "9001:9001"
    volumes:
      - ./www:/var/www/html
      - ./data/php-fpm/php.ini:/usr/local/etc/php/php.ini
