version: '2'
services:
    php:
        container_name: php
        dahaitech/docker-lanmp:php_mount_nginx-5.6
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/usr/share/nginx/html
            - ./data/nginx:/etc/nginx/conf.d
        volumes_from:
            - nginx
    nginx:
        container_name: nginx
        image: dahaitech/docker-lanmp:php_mount_nginx
    mariadb:
        container_name: mariadb
        image: univunix/alpine-mariadb
        ports:
            - "3306:3306"
        environment:
            DB_USER: root
            DB_PASS: a123456
