webserver:
  build: ./webserver
  dockerfile: Dockerfile
  container_name: webserver
  ports:
    - "80:80"
  links:
    # - webdata
    - db
  volumes:
    # - /Users/yeyou2:/var/www/html
    - ./apache/sites-enabled:/etc/apache2/sites-enabled
  volumes_from:
    - webdata
# dbdata:
  # image: alpine
  # container_name: dbdata
  # volumes:
    # - /var/lib/mysql
  # entrypoint:
    # - /bin/sh
db:
  image: percona
  container_name: db
  ports:
    - "3306:3306"
  volumes:
    - ./percona:/var/lib/mysql
    # - ./db/conf.d:/etc/mysql/conf.d
  # volumes_from:
  #   - samba_data
  environment:
    MYSQL_ROOT_PASSWORD: a123456

# samba_data:
  # build: ./samba_data
  # # volumes:
    # # - /samba_data
  # ports:
    # - "139:139"
    # - "445:445"
  # container_name: samba_data

webdata:
  build: ./webdata
  container_name: webdata
  environment:
    RSYNC_INTERVAL: 1
  volumes:
    - ./data/:/webdata
  ports:
    - "139:139"
    - "445:445"
  # entrypoint:
  #   - /start
  #   - -av
  #   # - --delete
  #   # - --delete-excluded
  #   - --include-from=/docker-rsync.include
  #   - --exclude-from=/docker-rsync.exclude
  #   - /webdata/
  #   - /var/www/html/
