version: '2'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/alpine/nginx/root/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/alpine/nginx/root/etc/nginx/ssl:/etc/nginx/ssl
      - ./data/alpine/nginx/root/etc/nginx/vhost:/etc/nginx/vhost
      - ./www:/var/www/html
    networks:
      app_net:
        ipv4_address: 172.16.1.2
        # ipv6_address: 2001:3984:3989::10
  php-fpm56:
    container_name: php-fpm56
    build:
      context: ./php-fpm
      dockerfile: Dockerfile_56
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./data/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./data/log:/var/log
      - ./data/tmp:/tmp
    networks:
      app_net:
        ipv4_address: 172.16.1.3
  samba:
    container_name: samba
    build: ./samba
    volumes:
      - ./:/shared
    ports:
      - "137-139:137-139"
      - "445:445"
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
      # - subnet: 2001:3984:3989::/64
      #   gateway: 2001:3984:3989::1
